use b2

; 

select ts.T_Belopp, ts.T_Belopp_Brutto, t.*
from (SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,
personnummer,efternamn,förnamn,[registrerat datum],betalning_typ,
konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar,
betalnings_underlag_Kommentar,Fördelning,
betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms,moms,calc_avdrag,avdrag,Belopp,
checkable,dödsboejklart,KontoOK,status, 1 antal_underlag ,
betalning_Underlag_id,bg_procent_av_orginal
from v_betalning_summering --_obetald  
where( datediff(hh,[Registrerat datum] , '2017-05-15 00:01')<0 and datediff(hh,[Registrerat datum] , '2018-05-29 23:59')>0 
and kontoOK=1 and DödsBoEjKlart=0  
and (rtrim(mottagare_typ) like 'U%' or rtrim(mottagare_typ) like 'R%' or rtrim(mottagare_typ) like 'O%') )) t 
join 
(select [Namn_Personnummer_grupp],sum(isnull(CALC_Belopp_NETTO,0.0)) T_Belopp,sum(isnull(Belopp,0.0)) T_Belopp_Brutto 
from v_betalning_summering --_obetald  
where( datediff(hh,[Registrerat datum] , '2017-05-15 00:01')<0 and datediff(hh,[Registrerat datum] , '2018-05-29 23:59')>0 
and kontoOK=1 and DödsBoEjKlart=0  --and STATUS !='BETALD'  
and (rtrim(mottagare_typ) like 'U%' or rtrim(mottagare_typ) like 'R%' or rtrim(mottagare_typ) like 'O%') )
group by  [Namn_Personnummer_grupp]
having sum(CALC_Belopp_NETTO)>100
) ts on ts.Namn_Personnummer_grupp =t.[Namn_Personnummer_grupp] 


order by efternamn,förnamn,[registrerat datum]; 


--8 s 9331
select ts.T_Belopp, ts.T_Belopp_Brutto, t.* 
from (
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,
personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar,
convert(varchar,count(*)) + 'Flera underlag '  betalnings_underlag_Kommentar,KontoOK,
min([Registrerat datum]) [Registrerat datum] ,sum(Belopp)/sum(betalning_underlag_belopp) Fördelning,sum(betalning_underlag_belopp) betalning_underlag_belopp,sum(CALC_Belopp_NETTO) CALC_Belopp_NETTO,sum(calc_moms) calc_moms,sum(calc_moms)/SUM(belopp) moms,sum(calc_avdrag) calc_avdrag,sum(calc_avdrag)/SUM(belopp) avdrag,sum(Belopp) Belopp,max(checkable) checkable,
min(dödsboejklart) dödsboejklart,max(status) status, COUNT(*) antal_underlag ,min(betalning_Underlag_id) betalning_Underlag_id,0 bg_procent_av_orginal 
from v_betalning_summering  where( datediff(hh,[Registrerat datum] , '2017-05-16 00:01')<0 and datediff(hh,[Registrerat datum] , '2018-05-30 23:59')>0 and kontoOK=1 and DödsBoEjKlart=0 )
group by [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar,KontoOK

 ) t   join (select [Namn_Personnummer_grupp],sum(isnull(CALC_Belopp_NETTO,0.0)) T_Belopp,sum(isnull(Belopp,0.0)) T_Belopp_Brutto from v_betalning_summering  where(   datediff(hh,[Registrerat datum] , '2017-05-16 00:01')<0 and datediff(hh,[Registrerat datum] , '2018-05-30 23:59')>0 and kontoOK=1 and DödsBoEjKlart=0 ) group by  [Namn_Personnummer_grupp]  having(sum(CALC_Belopp_NETTO) > 100) )  ts on ts.Namn_Personnummer_grupp =t.[Namn_Personnummer_grupp]  order by efternamn,förnamn,[registrerat datum]; 




 select ts.T_Belopp, ts.T_Belopp_Brutto, t.* from (SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, convert(varchar,count(*)) + ' st. underlag '  betalnings_underlag_Kommentar,KontoOK,min([Registrerat datum]) [Registrerat datum] ,sum(Belopp)/sum(betalning_underlag_belopp) Fördelning,sum(betalning_underlag_belopp) betalning_underlag_belopp,sum(CALC_Belopp_NETTO) CALC_Belopp_NETTO,sum(calc_moms) calc_moms,sum(calc_moms)/SUM(belopp) moms,sum(calc_avdrag) calc_avdrag,sum(calc_avdrag)/SUM(belopp) avdrag,sum(Belopp) Belopp,max(checkable) checkable,min(dödsboejklart) dödsboejklart,max(status) status, COUNT(*) antal_underlag ,min(betalning_Underlag_id) betalning_Underlag_id,0 bg_procent_av_orginal from v_betalning_summering  where( datediff(hh,[Registrerat datum] , '2017-05-16 00:01')<0 and datediff(hh,[Registrerat datum] , '2018-06-01 23:59')>0 and kontoOK=1 and DödsBoEjKlart=0 ) group by [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar,KontoOK ) t   join (select [Namn_Personnummer_grupp],sum(isnull(CALC_Belopp_NETTO,0.0)) T_Belopp,sum(isnull(Belopp,0.0)) T_Belopp_Brutto from v_betalning_summering  where(   datediff(hh,[Registrerat datum] , '2017-05-16 00:01')<0 and datediff(hh,[Registrerat datum] , '2018-06-01 23:59')>0 and kontoOK=1 and DödsBoEjKlart=0 ) group by  [Namn_Personnummer_grupp]  having(sum(CALC_Belopp_NETTO) > 100) )  ts on ts.Namn_Personnummer_grupp =t.[Namn_Personnummer_grupp]  order by efternamn,förnamn,[registrerat datum]; 



 select *  from bus.dbo.Rattighetshavare where Nr=1874

 select ts.T_Belopp, ts.T_Belopp_Brutto, t.* 
 from (SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal
		from v_betalning_summering  
		where( datediff(hh,[Registrerat datum] , '2018-05-18 00:01')<0 
			and datediff(hh,[Registrerat datum] , '2018-06-01 23:59')>0 
			and kontoOK=1 
			and DödsBoEjKlart=0  
			and STATUS !='BETALD'  
			and (rtrim(mottagare_typ) like 'U%' or rtrim(mottagare_typ) like 'R%' or rtrim(mottagare_typ) like 'O%')  
			and mottagare_id = 1874  
			and mottagare_typ = 'R') ) t   join (select [Namn_Personnummer_grupp],sum(isnull(CALC_Belopp_NETTO,0.0)) T_Belopp,sum(isnull(Belopp,0.0)) T_Belopp_Brutto from v_betalning_summering  where(   datediff(hh,[Registrerat datum] , '2018-05-18 00:01')<0 and datediff(hh,[Registrerat datum] , '2018-06-01 23:59')>0 and kontoOK=1 and DödsBoEjKlart=0  and STATUS !='BETALD'  and (rtrim(mottagare_typ) like 'U%' or rtrim(mottagare_typ) like 'R%' or rtrim(mottagare_typ) like 'O%')  and mottagare_id = 1874  and mottagare_typ = 'R') group by  [Namn_Personnummer_grupp]  having(sum(CALC_Belopp_NETTO) > 100) )  ts on ts.Namn_Personnummer_grupp =t.[Namn_Personnummer_grupp]  order by efternamn,förnamn,[registrerat datum]; 




			select ts.T_Belopp, ts.T_Belopp_Brutto, t.* 
			from (SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from v_betalning_summering  where( datediff(hh,[Registrerat datum] , '2017-05-24 00:01')<0 and datediff(hh,[Registrerat datum] , '2018-06-07 23:59')>0 and kontoOK=1 and DödsBoEjKlart=0  and STATUS !='BETALD'  and (rtrim(mottagare_typ) like 'S%')  and mottagare_id = 4  and mottagare_typ = 'S'   and betalning_typ = 'FÖLJERÄTT') ) t   join (select [Namn_Personnummer_grupp],sum(isnull(CALC_Belopp_NETTO,0.0)) T_Belopp,sum(isnull(Belopp,0.0)) T_Belopp_Brutto from v_betalning_summering  where(   datediff(hh,[Registrerat datum] , '2017-05-24 00:01')<0 and datediff(hh,[Registrerat datum] , '2018-06-07 23:59')>0 and kontoOK=1 and DödsBoEjKlart=0  and STATUS !='BETALD'  and (rtrim(mottagare_typ) like 'S%')  and mottagare_id = 4  and mottagare_typ = 'S'   and betalning_typ = 'FÖLJERÄTT') group by  [Namn_Personnummer_grupp]  having(sum(CALC_Belopp_NETTO) > 100) )  ts on ts.Namn_Personnummer_grupp =t.[Namn_Personnummer_grupp]  order by efternamn,förnamn,[registrerat datum]; 
			select COUNT(*) from v_betalning_summering_obetald


			select DATEPART(YYYY,skapad),COUNT(*) from 			betalning_godkänd group by DATEPART(YYYY,skapad)


		SELECT *,1 antal_underlag from v_betalning_summering_obetald  
		where( datediff(hh,[Registrerat datum] , '2010-05-24 00:01')<0 
		and datediff(hh,[Registrerat datum] , '2018-06-07 23:59')>0 
		and kontoOK=1 
		and DödsBoEjKlart=0  
		and STATUS !='BETALD'  
		and mottagare_id = 3470  
		and mottagare_typ = 'R'   
		and betalning_typ = 'REPRO'   
		and upphovsman_ID = '6768') 

			select * from betalning_transaktion
			update betalning_godkänd set betalning_post_id=NULL where datediff(dd,skapad,'2018-06-05')<=0
			
			select * from --delete 
			betalning_post where datediff(dd,skapad,'2018-06-05')<=0
			select * from --delete
			betalning_godkänd where betalning_post_id is NULL and datediff(dd,skapad,'2018-06-05')<=0
			


			SELECT *, 1 antal_underlag from v_betalning_summering  
			where( datediff(hh,[Registrerat datum] , '2015-05-25 00:01')<0 and datediff(hh,[Registrerat datum] , '2018-06-08 23:59')>0 
			and kontoOK=1 and DödsBoEjKlart=0  and STATUS !='BETALD'  and Namn_Personnummer_grupp = 'ADAGP,  ()'   
			and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '5283')    order by efternamn,förnamn,[registrerat datum]; 




select ts.T_Belopp, ts.T_Belopp_Brutto, t.* 
from (SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, convert(varchar,count(*)) + ' st. underlag '  betalnings_underlag_Kommentar,KontoOK,min([Registrerat datum]) [Registrerat datum] ,sum(Belopp)/sum(betalning_underlag_belopp) Fördelning,sum(betalning_underlag_belopp) betalning_underlag_belopp,sum(CALC_Belopp_NETTO) CALC_Belopp_NETTO,sum(calc_moms) calc_moms,sum(calc_moms)/SUM(belopp) moms,sum(calc_avdrag) calc_avdrag,sum(calc_avdrag)/SUM(belopp) avdrag,sum(Belopp) Belopp,max(checkable) checkable,min(dödsboejklart) dödsboejklart,max(status) status, COUNT(*) antal_underlag ,min(betalning_Underlag_id) betalning_Underlag_id,0 bg_procent_av_orginal 
	from v_betalning_summering
	--where( datediff(hh,[Registrerat datum] , '2010-05-24 00:01')<0 and datediff(hh,[Registrerat datum] , '2018-06-07 23:59')>0 and kontoOK=1 and DödsBoEjKlart=0  ) 
	group by [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar,KontoOK
	) t   
join 
	(select [Namn_Personnummer_grupp],sum(isnull(CALC_Belopp_NETTO,0.0)) T_Belopp,sum(isnull(Belopp,0.0)) T_Belopp_Brutto 
	from v_betalning_summering  
--	where(   datediff(hh,[Registrerat datum] , '2010-05-24 00:01')<0 and datediff(hh,[Registrerat datum] , '2018-06-07 23:59')>0 and kontoOK=1 and DödsBoEjKlart=0) 
	group by  [Namn_Personnummer_grupp]  
	having(sum(CALC_Belopp_NETTO) > 100) 
	)  ts on ts.Namn_Personnummer_grupp =t.[Namn_Personnummer_grupp]  order by efternamn,förnamn,[registrerat datum]; 

	
if OBJECT_ID('tempdb..#t') is not null drop table  #t
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,
mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,
konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum] , Fördelning,betalning_underlag_belopp, CALC_Belopp_NETTO,calc_moms, moms, calc_avdrag, avdrag, Belopp,checkable checkable,dödsboejklart,status status,1 antal_underlag ,betalning_Underlag_id betalning_Underlag_id,0 bg_procent_av_orginal 
into #t
	from v_betalning_summering
	--where( datediff(hh,[Registrerat datum] , '2010-05-24 00:01')<0 and datediff(hh,[Registrerat datum] , '2018-06-07 23:59')>0 and kontoOK=1 and DödsBoEjKlart=0  ) 
	
create INDEX x_Upphovsman on #t (Upphovsman_ID)
create INDEX x_MottagarTyp on #t ( mottagare_id,mottagare_typ)
create INDEX x_BetalningTyp on #t (betalning_typ	)

SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 921  and mottagare_typ = 'R'   and betalning_typ = 'KR-KF'   and upphovsman_ID = '6439'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 921  and mottagare_typ = 'R'   and betalning_typ = 'KR-MUS'   and upphovsman_ID = '6439'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 921  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '6439'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 2104  and mottagare_typ = 'R'   and betalning_typ = 'KR-KOM'   and upphovsman_ID = '7390'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 2104  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '7390'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 2017  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '5581'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 1874  and mottagare_typ = 'R'   and betalning_typ = 'KR-MUS'   and upphovsman_ID = '13748'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 1874  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '13748'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 7  and mottagare_typ = 'U'   and betalning_typ = 'KR-KOM'   and upphovsman_ID = '7'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 6574  and mottagare_typ = 'U'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '6574'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 3579  and mottagare_typ = 'R'   and betalning_typ = 'REPRO'   and upphovsman_ID = '4287'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 3579  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '4287'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 3579  and mottagare_typ = 'R'   and betalning_typ = 'ST'   and upphovsman_ID = '4287'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 4467  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '6757'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 4467  and mottagare_typ = 'R'   and betalning_typ = 'REPRO'   and upphovsman_ID = '6757'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 4361  and mottagare_typ = 'R'   and betalning_typ = 'REPRO'   and upphovsman_ID = '5725'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 4361  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '5725'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 4361  and mottagare_typ = 'R'   and betalning_typ = 'TVCOPY'   and upphovsman_ID = '5725'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 4361  and mottagare_typ = 'R'   and betalning_typ = 'KR-MUS'   and upphovsman_ID = '5725'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 23074  and mottagare_typ = 'U'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '23074'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 13  and mottagare_typ = 'U'   and betalning_typ = 'KR-MUS'   and upphovsman_ID = '13'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 13  and mottagare_typ = 'U'   and betalning_typ = 'REPRO'   and upphovsman_ID = '13'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 5296  and mottagare_typ = 'U'   and betalning_typ = 'KR'   and upphovsman_ID = '5296'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 5296  and mottagare_typ = 'U'   and betalning_typ = 'KR-MUS'   and upphovsman_ID = '5296'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 5296  and mottagare_typ = 'U'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '5296'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 12092  and mottagare_typ = 'U'   and betalning_typ = 'REPRO'   and upphovsman_ID = '12092'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 3909  and mottagare_typ = 'R'   and betalning_typ = 'REPRO'   and upphovsman_ID = '4813'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 22001  and mottagare_typ = 'U'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '22001'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 10394  and mottagare_typ = 'U'   and betalning_typ = 'REPRO'   and upphovsman_ID = '10394'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 4145  and mottagare_typ = 'R'   and betalning_typ = 'KR-MUS'   and upphovsman_ID = '5821'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 4145  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '5821'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 5906  and mottagare_typ = 'U'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '5906'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 20568  and mottagare_typ = 'U'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '20568'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 1053  and mottagare_typ = 'R'   and betalning_typ = 'KR-MUS'   and upphovsman_ID = '5297'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 1053  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '5297'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 1520  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '2108'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 3005  and mottagare_typ = 'U'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '3005'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 9600  and mottagare_typ = 'U'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '9600'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 6186  and mottagare_typ = 'U'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '6186'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 1739  and mottagare_typ = 'R'   and betalning_typ = 'REPRO'   and upphovsman_ID = '5120'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 1739  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '5120'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 1739  and mottagare_typ = 'R'   and betalning_typ = 'KR-MUS'   and upphovsman_ID = '5120'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 4079  and mottagare_typ = 'R'   and betalning_typ = 'REPRO'   and upphovsman_ID = '5227'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 4079  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '5227'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 4080  and mottagare_typ = 'R'   and betalning_typ = 'REPRO'   and upphovsman_ID = '5227'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 4080  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '5227'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 3012  and mottagare_typ = 'U'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '3012'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 10398  and mottagare_typ = 'U'   and betalning_typ = 'REPRO'   and upphovsman_ID = '10398'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 805  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '70'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 805  and mottagare_typ = 'R'   and betalning_typ = 'REPRO'   and upphovsman_ID = '70'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 15  and mottagare_typ = 'R'   and betalning_typ = 'FÖLJERÄTT'   and upphovsman_ID = '70'; 
SELECT [Namn_Personnummer_grupp],mottagare_id,mottagare_typ,mottagare_personnummer,mottagare_efternamn,mottagare_förnamn,upphovsman_ID,personnummer,efternamn,förnamn,betalning_typ,konto_typ_kortnamn,Adress_Kommentar,Konto_Kommentar, betalnings_underlag_Kommentar,KontoOK,[Registrerat datum],Fördelning, betalning_underlag_belopp,CALC_Belopp_NETTO,calc_moms, moms,calc_avdrag,avdrag,Belopp,checkable,dödsboejklart,status, 1 antal_underlag , betalning_Underlag_id,bg_procent_av_orginal from #t where mottagare_id = 15  and mottagare_typ = 'R'   and betalning_typ = 'REPRO'   and upphovsman_ID = '70'; 


select * from bus.dbo.Systerorganisation
select * from bus.dbo.betalningssatt where nr=3904
select * from bus.dbo.Kontotyp